name: 'rail_dbt'
version: '1.0.0'
config-version: 2

profile: 'rail_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  rail_dbt:
    +materialized: view


    gold:
      +schema: GOLD
      +materialized: table